service: soldier-trades-tracker
image: ghcr.io/santiagogabrielcastillo/soldier-trades-tracker

servers:
  web:
    - 204.168.208.150
  job:
    hosts:
      - 204.168.208.150
    cmd: bin/jobs

proxy:
  ssl: true
  host: soldier-trades.trade
  app_port: 3000

registry:
  server: ghcr.io
  username: santiagogabrielcastillo
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  remote: ssh://root@204.168.208.150

env:
  clear:
    RAILS_SERVE_STATIC_FILES: "true"
    REGISTRATION_OPEN: "true"
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - QUEUE_DATABASE_URL
    - ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
    - ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
    - ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
    - COINGECKO_API_KEY
    - IOL_USERNAME
    - IOL_PASSWORD

accessories:
  postgres:
    image: postgres:16
    host: 204.168.208.150
    port: "127.0.0.1:5432:5432"
    env:
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
